# -*- coding: utf-8 -*-
"""ATART Pong.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EG0FI5YclZEf-qVFkK5UpzuNQzCNcKK5
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/shreramsp/atari-pong-dqn.git
# %cd atari-pong-dqn

!pip install -q gymnasium[atari] ale-py opencv-python-headless tensorboardX

!nvidia-smi

!nohup python 02_dqn_pong.py --cuda > training.log 2>&1 &

# Commented out IPython magic to ensure Python compatibility.
# %load_ext tensorboard
# %tensorboard --logdir runs

!tail -n 20 training.log

!ps aux | grep 02_dqn_pong
